# Generated by Django 5.2.8 on 2026-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_picture_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="creator_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_creator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_listener",
            field=models.BooleanField(default=True),
        ),
    ]
